version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-sample-stepfunctions"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16uwd3xy9m0si"
s3_prefix = "sam-sample-stepfunctions"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

