AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sample-stepfunctions

  Sample SAM Template for sample-stepfunctions
  
Parameters:
  MasterSecretArn:
    Description: Master Secret ARN
    Type: String
  MasterSecretsManagerKey:
    Description: KMS Key for the use of secrets across accounts
    Type: String
  Stage:
    Description: Environment
    Type: String

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev  

  BranchValidationFailedSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub 'branch-validation-sns-topic'
      TopicName: !Sub 'branch-validation-topic'

  UpdataClassInfoSuccessSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub 'update-class-info-sns-topic'
      TopicName: !Sub 'update-class-info-topic'

  UpdateClassInfoStateMachineLogs:
    Type: AWS::Logs::LogGroup

  UpdateClassInfoStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/update_class_info.asl.json
      DefinitionSubstitutions:
        BranchCheckerFunctionArn: !GetAtt BranchCheckerFunction.Arn
        UpdateClassInfoFunctionArn: !GetAtt UpdateClassInfoFunction.Arn
        BranchValidationFailedSNSTopic: !Ref BranchValidationFailedSNSTopic
        UpdataClassInfoSuccessSNSTopic: !Ref UpdataClassInfoSuccessSNSTopic
#      Logging:
#        Destinations:
#          - CloudWatchLogsLogGroup:
#              LogGroupArn: !GetAtt UpdateClassInfoStateMachineLogs.Arn
#        IncludeExecutionData: true
#        Level: ALL
      Events: # Stepfunctions eventSource - More details on https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-statemachineeventsource.html
        HttpRequest:
          Type: Api
          Properties:
            Method: POST
            Path: /request
            RestApiId:
              Ref: ApiGatewayApi
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref BranchCheckerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref UpdateClassInfoFunction
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt BranchValidationFailedSNSTopic.TopicName
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt UpdataClassInfoSuccessSNSTopic.TopicName

  BranchCheckerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/branch-checker/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment: 
        Variables:
          tablename: !Ref BranchInfoTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BranchInfoTable

  UpdateClassInfoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/update-class-info/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment: 
        Variables:
          tablename: !Ref ClassInfoTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref ClassInfoTable

  ClassInfoTable:
    Type: AWS::Serverless::SimpleTable # More info about SimpleTable Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
    Properties:
      PrimaryKey:
        Name: ClassId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
 
  BranchInfoTable:
    Type: AWS::Serverless::SimpleTable # More info about SimpleTable Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
    Properties:
      PrimaryKey:
        Name: branchCode
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1        

Outputs:
  UpdateClassInfoStateMachineArn:
    Description: "Update Class Information state machine ARN"
    Value: !Ref UpdateClassInfoStateMachine
  UpdateClassInfoStateMachineRole:
    Description: "IAM Role created for Update Class Information state machine based on the specified SAM Policy Templates"
    Value: !GetAtt UpdateClassInfoStateMachineRole.Arn
